services:
  api:
    build: .
    image: produtosapi:local
    ports:
      - "8080:8080"
    depends_on:
      - migrator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ProdutosAPI=Server=sqlserver,1433;Database=Produtos;User Id=sa;Password=Password@1234;TrustServerCertificate=True;
  sqlserver:  
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password@1234
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Password@1234 -Q \"SELECT 1\" -b -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrator
    container_name: migrator
    depends_on:
      sqlserver:
        condition: service_healthy
    entrypoint: ["dotnet", "ef", "database", "update", "--project", "ProdutosAPI.csproj"]
    volumes:
      - sql_data:/var/opt/mssql
volumes:
  sql_data: